function build_LEO_EMC_Sim()
% build_LEO_EMC_Sim
% 一键生成 Simulink 模型：LEO卫星通信 EMC（通信视角）仿真骨架
%
% 依赖（推荐）：
%  - Simulink
%  - Communications Toolbox（用于QPSK调制/解调、卷积码/Viterbi、误码统计等模块）
%
% 生成：
%  - LEO_EMC_Sim_Simulink.slx

model = 'LEO_EMC_Sim_Simulink';
if bdIsLoaded(model); close_system(model,0); end
if exist([model '.slx'],'file'); delete([model '.slx']); end

new_system(model);
open_system(model);

% ---------- 全局参数（写入 Base Workspace，方便外行只改这里） ----------
cfg = defaultCfg();
assignin('base','cfg',cfg);

% ---------- 画布基础设置 ----------
set_param(model,'StopTime','cfg.sim.StopTime');
set_param(model,'Solver','FixedStepDiscrete');
set_param(model,'FixedStep','cfg.sim.Ts');

% ---------- 添加子系统：TX / Channel+EMC / RX / Metrics ----------
add_block('built-in/Subsystem',[model '/TX'], 'Position',[80 80 240 240]);
add_block('built-in/Subsystem',[model '/Channel_EMC'], 'Position',[320 80 520 240]);
add_block('built-in/Subsystem',[model '/RX'], 'Position',[600 80 760 240]);
add_block('built-in/Subsystem',[model '/Metrics'], 'Position',[840 80 1020 240]);

% 顶层连接：TX -> Channel_EMC -> RX -> Metrics
add_line(model,'TX/1','Channel_EMC/1','autorouting','on');
add_line(model,'Channel_EMC/1','RX/1','autorouting','on');
add_line(model,'RX/1','Metrics/1','autorouting','on');

% ---------- 构建 TX ----------
buildTX([model '/TX']);

% ---------- 构建 Channel + EMC ----------
buildChannelEMC([model '/Channel_EMC']);

% ---------- 构建 RX ----------
buildRX([model '/RX']);

% ---------- 构建 Metrics ----------
buildMetrics([model '/Metrics']);

% ---------- 美化布局 ----------
set_param([model '/TX'],'BackgroundColor','lightBlue');
set_param([model '/Channel_EMC'],'BackgroundColor','lightYellow');
set_param([model '/RX'],'BackgroundColor','lightBlue');
set_param([model '/Metrics'],'BackgroundColor','lightGreen');

save_system(model);
disp(['✅ 已生成模型：' model '.slx']);
disp('下一步：运行 run_LEO_EMC_Sim.m 来仿真并出图。');
end

% =================================================================
%                       默认参数（外行只改这里）
% =================================================================
function cfg = defaultCfg()
cfg.sim.Ts = 1/1e6;                 % 离散步长(秒) = 1/Rs
cfg.sim.StopTime = '0.2';           % 仿真时长（秒）

cfg.phy.Rs = 1e6;                   % 符号率(Hz)
cfg.phy.frameBits = 1000;           % 每帧信息比特数
cfg.phy.preambleHalfLen = 8;        % 重复前导半段长度 L
cfg.phy.preambleReps = 4;           % 重复次数（>=2）

cfg.chan.enableRician = true;
cfg.chan.K_dB = 6;                  % Rician K(dB)

% LEO Doppler（可在 run脚本里改成随时间变化的序列/函数）
cfg.leo.fD_Hz = 30e3;               % 多普勒频偏(Hz)（简化为常数）

% 噪声/干扰（通信视角 EMC）
cfg.noise.EbN0_dB = 8;              % 热噪声强度（粗略控制）
cfg.emc.type = 1;                   % 1=同频噪声 2=单音 3=脉冲 4=邻频等效 5=同址等效
cfg.emc.JS_dB = -5;                 % 干扰/信号 J/S(dB)
cfg.emc.toneOffset_Hz = 10e3;       % 单音干扰频偏（Hz）
cfg.emc.pulseDuty = 0.10;           % 脉冲占空比
cfg.emc.pulsePeriodSym = 200;       % 脉冲周期(符号)
cfg.emc.ACIR_dB = 30;               % 邻频等效（越大越好）
cfg.emc.cositeCoupling_dB = -60;    % 同址耦合(dB)
cfg.emc.cositeSrcP_dBW = 0;         % 同址源功率(dBW)

% CFO补偿
cfg.rx.cfoMethod = 2;               % 1=理想 2=前导估计
end

% =================================================================
%                           TX 子系统
% 输出：复基带符号流（含前导）
% =================================================================
function buildTX(path)
% 端口
add_block('built-in/Inport',[path '/In1'], 'Position',[20 40 50 60]); %#ok<NASGU>
add_block('built-in/Outport',[path '/Out1'],'Position',[380 120 410 140]);

% 1) 随机比特
add_block('simulink/Sources/Random Integer Generator',[path '/RandBits'], ...
    'Position',[60 90 170 140], ...
    'Maximum', '1', 'SampleTime','cfg.sim.Ts', 'SamplesPerFrame','cfg.phy.frameBits');

% 2) 卷积编码（需要 Comm Toolbox）
add_block('commtx/Convolutional Encoder',[path '/ConvEnc'], ...
    'Position',[200 90 280 140], ...
    'TrellisStructure','poly2trellis(7,[171 133])');

% 3) QPSK 调制（Rectangular QAM with M=4）
add_block('commtx/Rectangular QAM Modulator Baseband',[path '/QPSKMod'], ...
    'Position',[310 90 360 140], ...
    'ModulationOrder','4', 'BitInput','on', 'NormalizationMethod','Average power');

% 4) 前导插入（MATLAB Function Block：把重复前导 + payload 拼接）
add_block('simulink/User-Defined Functions/MATLAB Function',[path '/PreambleInsert'], ...
    'Position',[310 160 360 220]);
set_param([path '/PreambleInsert'], 'FunctionName','preamble_insert');

% 连接：RandBits->ConvEnc->QPSKMod->PreambleInsert->Out
add_line(path,'RandBits/1','ConvEnc/1','autorouting','on');
add_line(path,'ConvEnc/1','QPSKMod/1','autorouting','on');
add_line(path,'QPSKMod/1','PreambleInsert/1','autorouting','on');
add_line(path,'PreambleInsert/1','Out1/1','autorouting','on');

% 写入 MATLAB Function 代码
code = [
"function y = preamble_insert(payloadSym)", newline, ...
"%#codegen", newline, ...
"% payloadSym: 复基带payload（列向量）", newline, ...
"% y: 前导 + payload", newline, ...
"L = cfg.phy.preambleHalfLen;", newline, ...
"reps = cfg.phy.preambleReps;", newline, ...
"% 生成一段固定前导（为了可复现，使用固定伪随机序列）", newline, ...
"persistent p0;", newline, ...
"if isempty(p0)", newline, ...
"  rng(1);", newline, ...
"  b = randi([0 1], 2*L, 1);", newline, ...
"  p0 = qpsk_mod_local(b);", newline, ...
"end", newline, ...
"preamble = repmat(p0, reps, 1);", newline, ...
"y = [preamble; payloadSym(:)];", newline, ...
"", newline, ...
"function sym = qpsk_mod_local(bits)", newline, ...
"  b0 = bits(1:2:end); b1 = bits(2:2:end);", newline, ...
"  I = 1 - 2*b0; Q = 1 - 2*b1;", newline, ...
"  sym = (I + 1j*Q)/sqrt(2);", newline, ...
"end", newline ...
];
set_param([path '/PreambleInsert'], 'Script', code);
end

% =================================================================
%                   Channel + EMC 子系统
% 输入：tx复基带；输出：rx复基带（含噪声+干扰+多普勒+衰落）
% =================================================================
function buildChannelEMC(path)
add_block('built-in/Inport',[path '/In1'], 'Position',[20 120 50 140]);
add_block('built-in/Outport',[path '/Out1'],'Position',[500 120 530 140]);

% 1) Rician 平坦衰落（Comm Toolbox）
add_block('commchan/Rician Fading Channel',[path '/Rician'], ...
    'Position',[80 90 180 150], ...
    'KFactor','10^(cfg.chan.K_dB/10)', ...
    'PathDelays','0', ...
    'AveragePathGains','0', ...
    'DopplerSpectrum','doppler(''Jakes'')', ...
    'MaximumDopplerShift','0'); % 我们把多普勒放到 Frequency Offset 模块

% 2) 多普勒：Frequency Offset
add_block('commchan/Phase/Frequency Offset',[path '/FreqOffset'], ...
    'Position',[210 90 320 150], ...
    'FrequencyOffset','cfg.leo.fD_Hz', ...
    'SampleRate','cfg.phy.Rs');

% 3) 干扰源生成（MATLAB Function：根据cfg.emc.type生成干扰波形）
add_block('simulink/User-Defined Functions/MATLAB Function',[path '/InterferenceGen'], ...
    'Position',[210 170 320 240]);
set_param([path '/InterferenceGen'], 'FunctionName','interf_gen');

% 4) 加法器：信号 + 干扰
add_block('simulink/Math Operations/Add',[path '/AddSigInt'], ...
    'Position',[350 110 380 140], ...
    'Inputs','++');

% 5) 噪声：AWGN Channel（Comm Toolbox）
add_block('commchan/AWGN Channel',[path '/AWGN'], ...
    'Position',[400 90 470 150], ...
    'EbNo','cfg.noise.EbN0_dB', ...
    'BitsPerSymbol','2', ...
    'SamplesPerSymbol','1');

% 连接
add_line(path,'In1/1','Rician/1','autorouting','on');
add_line(path,'Rician/1','FreqOffset/1','autorouting','on');
add_line(path,'FreqOffset/1','AddSigInt/1','autorouting','on');
add_line(path,'InterferenceGen/1','AddSigInt/2','autorouting','on');
add_line(path,'AddSigInt/1','AWGN/1','autorouting','on');
add_line(path,'AWGN/1','Out1/1','autorouting','on');

% 干扰生成 MATLAB Function 代码
code = [
"function i = interf_gen(x)", newline, ...
"%#codegen", newline, ...
"% x: 输入信号(复数)，只用于估算信号功率，输出同长度干扰 i", newline, ...
"sig = x(:);", newline, ...
"N = length(sig);", newline, ...
"Ps = mean(abs(sig).^2) + 1e-12;", newline, ...
"JS = 10^(cfg.emc.JS_dB/10);", newline, ...
"Pj = Ps * JS;", newline, ...
"t = (0:N-1).';", newline, ...
"switch cfg.emc.type", newline, ...
"  case 1 % 同频宽带噪声", newline, ...
"    i = sqrt(Pj/2) * (randn(N,1)+1j*randn(N,1));", newline, ...
"  case 2 % 单音干扰", newline, ...
"    A = sqrt(Pj);", newline, ...
"    f0 = cfg.emc.toneOffset_Hz;", newline, ...
"    i = A * exp(1j*2*pi*f0*t/cfg.phy.Rs);", newline, ...
"  case 3 % 脉冲噪声", newline, ...
"    duty = cfg.emc.pulseDuty;", newline, ...
"    per  = cfg.emc.pulsePeriodSym;", newline, ...
"    onN  = max(1, round(duty*per));", newline, ...
"    mask = false(N,1);", newline, ...
"    pos = 1;", newline, ...
"    while pos <= N", newline, ...
"      mask(pos:min(pos+onN-1,N)) = true;", newline, ...
"      pos = pos + per;", newline, ...
"    end", newline, ...
"    P_on = Pj / max(duty,1e-6);", newline, ...
"    i = zeros(N,1);", newline, ...
"    w = sqrt(P_on/2) * (randn(N,1)+1j*randn(N,1));", newline, ...
"    i(mask) = w(mask);", newline, ...
"  case 4 % 邻频等效（ACIR折算成等效本带干扰）", newline, ...
"    Ieq = Pj * 10^(-cfg.emc.ACIR_dB/10);", newline, ...
"    i = sqrt(Ieq/2) * (randn(N,1)+1j*randn(N,1));", newline, ...
"  case 5 % 同址等效：源功率+耦合折算为等效干扰", newline, ...
"    Psrc = 10^(cfg.emc.cositeSrcP_dBW/10);", newline, ...
"    coup = 10^(cfg.emc.cositeCoupling_dB/10);", newline, ...
"    Ieq = Psrc * coup;", newline, ...
"    i = sqrt(Ieq/2) * (randn(N,1)+1j*randn(N,1));", newline, ...
"  otherwise", newline, ...
"    i = zeros(N,1);", newline, ...
"end", newline ...
];
set_param([path '/InterferenceGen'], 'Script', code);
end

% =================================================================
%                           RX 子系统
% 输入：rx复基带（含前导）；输出：译码后的信息比特
% =================================================================
function buildRX(path)
add_block('built-in/Inport',[path '/In1'], 'Position',[20 120 50 140]);
add_block('built-in/Outport',[path '/Out1'],'Position',[520 120 550 140]);

% 1) CFO估计与补偿（MATLAB Function）
add_block('simulink/User-Defined Functions/MATLAB Function',[path '/CFOComp'], ...
    'Position',[90 80 220 160]);
set_param([path '/CFOComp'], 'FunctionName','cfo_comp');

% 2) QPSK 解调（Comm Toolbox）
add_block('commrx/Rectangular QAM Demodulator Baseband',[path '/QPSKDemod'], ...
    'Position',[260 80 340 160], ...
    'ModulationOrder','4', 'BitOutput','on', 'NormalizationMethod','Average power');

% 3) Viterbi译码（Comm Toolbox）
add_block('commrx/Viterbi Decoder',[path '/Viterbi'], ...
    'Position',[380 80 480 160], ...
    'TrellisStructure','poly2trellis(7,[171 133])', ...
    'InputFormat','Hard', ...
    'TracebackDepth','42', ...
    'TerminationMethod','Terminated');

% 连接
add_line(path,'In1/1','CFOComp/1','autorouting','on');
add_line(path,'CFOComp/1','QPSKDemod/1','autorouting','on');
add_line(path,'QPSKDemod/1','Viterbi/1','autorouting','on');
add_line(path,'Viterbi/1','Out1/1','autorouting','on');

% CFO补偿 MATLAB Function（重复前导估计或理想补偿）
code = [
"function y = cfo_comp(r)", newline, ...
"%#codegen", newline, ...
"% r: 输入复基带（含重复前导）", newline, ...
"% y: CFO补偿后输出", newline, ...
"rx = r(:);", newline, ...
"N = length(rx);", newline, ...
"Rs = cfg.phy.Rs;", newline, ...
"t = (0:N-1).';", newline, ...
"if cfg.rx.cfoMethod == 1", newline, ...
"  cfo_hat = cfg.leo.fD_Hz; % 理想", newline, ...
"else", newline, ...
"  L = cfg.phy.preambleHalfLen;", newline, ...
"  if N < 2*L", newline, ...
"    cfo_hat = 0;", newline, ...
"  else", newline, ...
"    r1 = rx(1:L); r2 = rx(L+1:2*L);", newline, ...
"    P = sum(conj(r1).*r2);", newline, ...
"    cfo_hat = angle(P) * Rs / (2*pi*L);", newline, ...
"  end", newline, ...
"end", newline, ...
"y = rx .* exp(-1j*2*pi*cfo_hat*t/Rs);", newline ...
];
set_param([path '/CFOComp'], 'Script', code);
end

% =================================================================
%                       Metrics 子系统
% 输入：译码后的信息比特；输出：误码率到工作区
% =================================================================
function buildMetrics(path)
add_block('built-in/Inport',[path '/In1'], 'Position',[20 120 50 140]);

% 参考比特：为了能算BER，这里再生成同样长度的随机源（演示用）
% 更严谨做法：把TX的原始比特也输出到Metrics做对齐比较
add_block('simulink/Sources/Random Integer Generator',[path '/RefBits'], ...
    'Position',[80 70 180 120], ...
    'Maximum','1','SampleTime','cfg.sim.Ts','SamplesPerFrame','cfg.phy.frameBits');

add_block('comm/Error Rate Calculation',[path '/ErrRate'], ...
    'Position',[220 90 360 150]);

add_block('simulink/Sinks/To Workspace',[path '/ToWS'], ...
    'Position',[400 100 480 140], ...
    'VariableName','errRate', 'SaveFormat','Array');

add_line(path,'RefBits/1','ErrRate/1','autorouting','on');
add_line(path,'In1/1','ErrRate/2','autorouting','on');
add_line(path,'ErrRate/1','ToWS/1','autorouting','on');

% 备注：这个Metrics是“演示型”。如果你要完全严谨：
% - 在TX里把原始信息比特 u 也输出一个端口
% - 顶层连接到Metrics用于真实对比
end
